/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ApplicationsIndexRouteImport } from "./routes/applications.index"
import { Route as ApplicationsNewRouteImport } from "./routes/applications.new"
import { Route as ApplicationsIdIndexRouteImport } from "./routes/applications.$id.index"
import { Route as ApplicationsIdEditRouteImport } from "./routes/applications.$id.edit"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: "/applications/",
  path: "/applications/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsNewRoute = ApplicationsNewRouteImport.update({
  id: "/applications/new",
  path: "/applications/new",
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdIndexRoute = ApplicationsIdIndexRouteImport.update({
  id: "/applications/$id/",
  path: "/applications/$id/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdEditRoute = ApplicationsIdEditRouteImport.update({
  id: "/applications/$id/edit",
  path: "/applications/$id/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/applications/new": typeof ApplicationsNewRoute
  "/applications/": typeof ApplicationsIndexRoute
  "/applications/$id/edit": typeof ApplicationsIdEditRoute
  "/applications/$id/": typeof ApplicationsIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/applications/new": typeof ApplicationsNewRoute
  "/applications": typeof ApplicationsIndexRoute
  "/applications/$id/edit": typeof ApplicationsIdEditRoute
  "/applications/$id": typeof ApplicationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/applications/new": typeof ApplicationsNewRoute
  "/applications/": typeof ApplicationsIndexRoute
  "/applications/$id/edit": typeof ApplicationsIdEditRoute
  "/applications/$id/": typeof ApplicationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/applications/new"
    | "/applications/"
    | "/applications/$id/edit"
    | "/applications/$id/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/applications/new"
    | "/applications"
    | "/applications/$id/edit"
    | "/applications/$id"
  id:
    | "__root__"
    | "/"
    | "/applications/new"
    | "/applications/"
    | "/applications/$id/edit"
    | "/applications/$id/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsNewRoute: typeof ApplicationsNewRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  ApplicationsIdEditRoute: typeof ApplicationsIdEditRoute
  ApplicationsIdIndexRoute: typeof ApplicationsIdIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/applications/": {
      id: "/applications/"
      path: "/applications"
      fullPath: "/applications/"
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/applications/new": {
      id: "/applications/new"
      path: "/applications/new"
      fullPath: "/applications/new"
      preLoaderRoute: typeof ApplicationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/applications/$id/": {
      id: "/applications/$id/"
      path: "/applications/$id"
      fullPath: "/applications/$id/"
      preLoaderRoute: typeof ApplicationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/applications/$id/edit": {
      id: "/applications/$id/edit"
      path: "/applications/$id/edit"
      fullPath: "/applications/$id/edit"
      preLoaderRoute: typeof ApplicationsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsNewRoute: ApplicationsNewRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  ApplicationsIdEditRoute: ApplicationsIdEditRoute,
  ApplicationsIdIndexRoute: ApplicationsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { startInstance } from "./start.ts"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
